version: '3'
services:
    mysql:
        image: mysql:5
        env_file: .env
    app:
        image: creativitykills/nginx-php-server:latest
        environment:
            LARAVEL: 1
            COMPOSER_DIRECTORY: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8080:80
