version: '3'
services:
    mysql:
        image: mysql:5
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: problem_sets
            MYSQL_USER: problem_sets
            MYSQL_PASSWORD: problem_sets
