version: '3'
services:
    mysql:
        image: mysql:5
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: problem_sets
            MYSQL_USER: problem_sets
            MYSQL_PASSWORD: problem_sets
    app:
        image: creativitykills/nginx-php-server:latest
        environment:
            LARAVEL: 1
            COMPOSER_DIRECTORY: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8080:80
